# Generated by Django 4.2.1 on 2023-05-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave', models.IntegerField()),
                ('start_question', models.IntegerField()),
                ('gifts', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('place_miem', models.CharField(blank=True, max_length=500)),
                ('place_pokrovka', models.CharField(blank=True, max_length=500)),
                ('place_basmach', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=50)),
                ('tg_id', models.IntegerField(unique=True)),
                ('start', models.IntegerField()),
                ('stage', models.IntegerField()),
                ('tries', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('wave', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
